name: Bug report
about: Create a report to help us improve
title: ''
labels: ['needs-triage']
assignees: ''

body: 
  - type: markdown
    attributes:
      value:  |
      
 - [ ] I have read the [FAQ](https://github.com/Genymobile/scrcpy/blob/master/FAQ.md).
 - [ ] I have searched in existing [issues](https://github.com/Genymobile/scrcpy/issues).
 - [ ] [Known Issues](https://github.com/Genymobile/scrcpy/labels/Known%20issue)

  - type: markdown
    attributes:
      value: |
        **Environment**
 
  - type: dropdown
    id: os
    attributes:
      label: Operating System
      options:
        - Debian
        - Windows
        - macOS
      description: Which operating system are you using?

  - type: input
    id: scrcpy-version
    attributes:
      label: scrcpy version
      description: What version of scrcpy are you using?
      placeholder: e.g. 1.12.1

  - type: dropdown
    id: install-method
    attributes:
      label: Installation method
      options:
        - Manual build
        - apt
        - snap
        - brew
        - Windows release
      description: How did you install the scrcpy?
      
  - type: input
    id: device-model
    attributes:
      label: Device model
      description: What is the model of your device?
      placeholder: Enter device model here

  - type: input
    id: android-version
    attributes:
      label: Android version
      description: What version of Android are you using?
      placeholder: e.g. 10

  - type: markdown
    attributes:
      value: |
        **Describe the bug**
        
#A clear and concise description of what the bug is.

#On errors, please provide the output of the console (and `adb logcat` if relevant).

  - type: textarea
    attributes:
      label: Please paste terminal output in a code block.
      placeholder: Paste your output here
      value: |
     
      render: shell

#Please do not post screenshots of your terminal, just post the content as text instead.
